### PR TITLE
[agent-a][issue #1314] Admit Tier5 create-flow fixtures

### LINKED ISSUE #1314: [maintenance] Tier5 create_flow_instance excluded fixtures still point at closed #416
## Category
Conformance / maintenance tracker hygiene.

## Finding
During PR #1307 review, the repo-wide auto_emit/create_flow_instance fixture probe found that `internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go` still excludes these fixtures with reason `legacy create_flow_instance action shape now rejected; fixture migration belongs to #416`:

- `test-create-flow-instance`
- `test-create-flow-instance-config`
- `test-create-flow-instance-duplicate`

Issue #416 is closed, so the skip reason now points at a completed tracker even though the fixtures remain excluded.

This is not a blocking #1307 finding: the live auto_emit runtime proof and the PR's direct/queued manager proof pass on the merge ref, and the skipped tier5 fixtures are not part of the approved #1297 child class closure. It is still a stale tracker-state problem that should not remain implicit.

## Expected
Either:

- migrate and unskip the three tier5 create_flow_instance fixtures, or
- retarget the exclusions to an open tracker that explicitly owns the remaining legacy action-shape/conformance gap.

## Acceptance
- `tier5ExcludedFixtures` no longer references closed #416 as the active owner.
- The three fixture dispositions are explicit: migrated/unskipped, or deliberately tracked by an open issue.
- If migrated, run the tier5 catalog E2E surface that includes these fixtures and verify no hidden auto_emit lifecycle-payload dependency remains.

### PR DESCRIPTION
**Pull request by yazzaoui**
Closes #1314

## Governing Context
- Pre-Implementation Coverage Audit: https://github.com/division-sh/swarm/issues/1314#issuecomment-4618501913
- Independent gate: https://github.com/division-sh/swarm/issues/1314#issuecomment-4618513193
- Binding spec/context: `platform-spec.yaml` `create_flow_instance` required fields, dynamic lifecycle creation, `config_from_payload_alignment`, and `auto_emit_on_create_surface`.

## Scope
- Admits all three Tier5 `create_flow_instance` fixtures together: base, config, and duplicate.
- Migrates base and duplicate fixtures to non-empty `config_from`.
- Aligns config fixture auto-emitted event schema with resolved `config_from` business payload only.
- Removes stale closed-#416 Tier5 exclusion accounting.
- Tightens catalog proof to assert one persisted `flow_instances` row and one auto-emitted event for the exact created instance.

## Semantic Migration
- New canonical owner: current `platform-spec.yaml` plus boot/runtime validation for `create_flow_instance` and auto-emit payload authority.
- Old invalid path: closed-#416 Tier5 exclusion entries, missing `config_from` fixture authoring, hidden lifecycle payload synthesis assumptions, and route-row-only `flow_instance_created` proof.
- Production paths checked: Tier5 catalog real-runtime admission, boot/runtime fixture execution, persisted flow instance rows, auto-emitted event rows, and sibling Tier9/Tier11 `flow_instance_created` fixture assertions.
- Migration complete for the approved #1314 child. Tier4/Tier11 stale #416 entries and #1304 remain split per gate.

## Proof
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_RealRuntime/(test-create-flow-instance|test-create-flow-instance-config|test-create-flow-instance-duplicate)$' -count=1`
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_(AreExplicitlyClassified|RealRuntime)$' -count=1`
- `go test ./internal/runtime/cataloge2e -run 'TestTier(9|11)' -count=1`
- `go test ./internal/runtime/cataloge2e -count=1`
- `go test ./internal/runtime/swarmflowtest -run 'TestCatalogFixtures_UseCanonicalCreateFlowInstanceAuthoring|TestValidateCatalogExpectedDocument' -count=1`
- `git diff --check`

## Full Suite Status
- Ran `go test ./... -count=1`.
- It failed only in `internal/store` on `TestSQLiteDynamicFlowActivationRequiredAgentsUsePipelineTransaction` and `TestSQLiteDynamicFlowActivationConcurrentFanOutChildrenPersist` with `event bus does not support derived flow-instance routing ...`.
- This PR has no `internal/store` diff; the focused failing package rerun reproduces the same failures outside the approved #1314 boundary.

### CODE REVIEW

**Comment by yazzaoui** [comment]
## Post-Implementation Proof Audit

**Exact semantic concepts changed**
- Tier5 `create_flow_instance` catalog fixture admission under the current required `config_from` contract.
- `auto_emit_on_create` proof for resolved flow-instance config/business payload only, without lifecycle-envelope payload synthesis.
- Catalog `flow_instance_created` proof surface for persisted `flow_instances` rows and exact auto-emitted event count.
- Tier5 stale closed-#416 exclusion accounting.

**Chosen working failure class closed entirely**
- `tier5.create_flow_instance_fixture_admission_current_spec`.

**Parent failure class above it**
- Immediate parent: Tier5 dynamic flow-instance lifecycle catalog conformance drift.
- Broader parent: excluded catalog fixture drift after platform contract migrations.

**Canonical owners after the change**
- `platform-spec.yaml`: `create_flow_instance` required fields, dynamic lifecycle creation, `config_from_payload_alignment`, and `auto_emit_on_create_surface`.
- `internal/runtime/bootverify/workflow_handler_contract_checks.go`: boot admission for handler action shape and payload completeness.
- `internal/runtime/pipeline/workflow_instance_activation.go`: runtime flow-instance activation and auto-emit source authority.
- `internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go`: Tier5 fixture inclusion/exclusion accounting and runtime execution selection.
- `internal/runtime/cataloge2e/assertions_harness_test.go`: catalog proof reader for persisted flow instance/config/auto-emit evidence.
- `tests/tier5-flow-lifecycle/test-create-flow-instance*`: authored fixture contracts and expected outcomes.

**Touched consumers and systematic-consumption audit**
- Tier5 fixture classifier: the three `test-create-flow-instance*` fixtures now consume the supported Tier5 runtime path and no longer bypass it through the exclusion map.
- Base fixture: moved to current `config_from` authoring and expected persisted instance/config/auto-emit proof.
- Config fixture: already consumed `config_from`; its worker auto-emit event schema now consumes the resolved config payload rather than an envelope-owned `entity_id` assumption.
- Duplicate fixture: moved to current `config_from` authoring and exact one-row/one-auto-emit proof for duplicate create rejection before side effects.
- Assertion harness: `flow_instance_created` now consumes the persisted `flow_instances` row as the authoritative proof, plus config JSON and exact auto-emitted event count.
- Sibling seams checked: Tier9 and Tier11 `flow_instance_created` fixtures still pass with the tightened assertion; Tier4/Tier11 stale #416 entries and #1304 remain split by the approved gate.

**Old paths now invalid, non-authoritative, or surviving**
- Invalid: stale Tier5 exclusion reasons pointing to closed #416.
- Invalid: base/duplicate fixtures without non-empty `config_from`.
- Invalid: hidden lifecycle-envelope payload synthesis for `auto_emit_on_create` business fields.
- Non-authoritative: route-row-only `flow_instance_created` proof; persisted `flow_instances` is the direct proof for instance creation.
- Still surviving and explicitly split: Tier4/Tier11 stale #416 exclusion cleanup and #1304 broader fixture family.

**Broader failure class and issue shape**
- Broader class: catalog fixture exclusion drift after spec/runtime contract migrations.
- The issue was symptom-shaped around a stale closed-#416 skip reason; the implementation treated that as entry evidence and closed all three Tier5 same-class fixtures together.

**Achieved closure level**
- Complete closure for `tier5.create_flow_instance_fixture_admission_current_spec`.
- Parent class remains open only for explicitly split sibling exclusions outside this gate.

**Remaining child-slice tail estimate**
- Unchanged from the refreshed pre-audit: Tier4/Tier11 stale #416 entries and #1304 are separate child/sibling work, medium confidence. Implementation did not discover another live Tier5 same-concept interpreter.

**Generic failing proof used or created**
- The previously excluded Tier5 fixtures are now executable under `TestTier5LifecycleCatalogFixtures_RealRuntime` and fail closed if they lose current-spec `config_from`, persisted instance proof, resolved config proof, or exact auto-emit proof.

**Watchlist decision**
- Primary mapping remains `/Users/youmew/dev/swarm-docs/docs/watchlists/maintenance-and-cleanup.yaml#invariant_suite_coverage`.
- `semantic-correctness.yaml#legacy_fixture_drift_after_runtime_contract_migrations` remains historical caution only for this PR.

**Architecture feedback and tracking decision**
- Smell: fixture exclusion maps can drift away from executable fixture contracts and closed issue state.
- Tracking decision: watchlist only through `maintenance-and-cleanup.yaml#invariant_suite_coverage`; no new issue needed for this #1314 slice.

**Manifestation coverage table**

| Manifestation | Status | Exact proof |
| --- | --- | --- |
| `test-create-flow-instance` stale exclusion / missing `config_from` | reproduced and fixed | focused Tier5 run proves boot/runtime admission, persisted `flow_instances` row, resolved config, and exact `worker-flow/worker-001/worker.ready` auto-emit |
| `test-create-flow-instance-config` timeout/config mismatch | reproduced and fixed | focused Tier5 run proves resolved `max_retries`/`timeout_ms` config payload and exact `worker-flow/worker-cfg-001/worker.ready` auto-emit |
| `test-create-flow-instance-duplicate` stale exclusion / duplicate side-effect risk | reproduced and fixed | focused Tier5 run proves exactly one persisted `worker-flow/worker-dup` row and exactly one `worker-flow/worker-dup/worker.ready` auto-emit |
| Tier5 closed-#416 exclusion accounting | reproduced and fixed | `TestTier5LifecycleCatalogFixtures_AreExplicitlyClassified` plus `rg` sweep over Tier5 fixture map/prose |
| Tier9/Tier11 consumers of `flow_instance_created` helper | execution-proven through the same corrected path | `go test ./internal/runtime/cataloge2e -run 'TestTier(9|11)' -count=1` |
| Tier4/Tier11 stale #416 exclusions | split / escalated as separate class | explicitly outside gate and left to sibling cleanup |
| #1304 fixture family | split / escalated as separate class | explicitly outside gate and not absorbed |

**Required supported-surface proof actually run**
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_RealRuntime/(test-create-flow-instance|test-create-flow-instance-config|test-create-flow-instance-duplicate)$' -count=1`
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_(AreExplicitlyClassified|RealRuntime)$' -count=1`
- `go test ./internal/runtime/cataloge2e -run 'TestTier(9|11)' -count=1`
- `go test ./internal/runtime/cataloge2e -count=1`
- `go test ./internal/runtime/swarmflowtest -run 'TestCatalogFixtures_UseCanonicalCreateFlowInstanceAuthoring|TestValidateCatalogExpectedDocument' -count=1`
- `git diff --check`

**Whole-suite status**
- Ran `go test ./... -count=1`.
- It failed only in `internal/store` on `TestSQLiteDynamicFlowActivationRequiredAgentsUsePipelineTransaction` and `TestSQLiteDynamicFlowActivationConcurrentFanOutChildrenPersist` with `event bus does not support derived flow-instance routing ...`.
- This PR has no `internal/store` diff, and the focused failing package rerun reproduced the same failures outside the approved #1314 boundary.

File: internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go [hunk 1]
```diff
@@ -15,6 +15,9 @@ type catalogExcludedFixture struct {
 
 var tier5LifecycleFixtures = []string{
 	"test-auto-emit-on-create",
+	"test-create-flow-instance",
+	"test-create-flow-instance-config",
+	"test-create-flow-instance-duplicate",
```
[the remark this answers is not in the document]
Comment (yazzaoui) [reply internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go:20]: Addressed in 71890c7c (`test: assert duplicate flow receipt failure`). The duplicate fixture now asserts the second trigger records `receipt_outcome: dead_letter` and `receipt_error_contains: "flow instance already exists: worker-flow/worker-dup"`; the catalog harness checks the persisted platform pipeline receipt side effects instead of relying on `Publish` returning an error. Proof rerun with isolated `GOCACHE=/tmp/swarm-go-cache-1314`: focused three-fixture Tier5 run, full Tier5 classification/runtime run, Tier9/Tier11 helper regression, full `internal/runtime/cataloge2e`, `internal/runtime/swarmflowtest` catalog validation, and `git diff --check`.

**Review by yazzaoui — COMMENTED** [review]
Findings:

1. Blocking: `internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go` is not gofmt-formatted. CI `test` fails in the formatting step with `Files not formatted: internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go`, and local `gofmt -l internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go` reproduces it. The required fix is just formatting the empty `tier5ExcludedFixtures` map: gofmt rewrites the current two-line empty literal to `var tier5ExcludedFixtures = map[string]catalogExcludedFixture{}`. Until this is fixed and CI is rerun, the PR is not merge-ready.

Process / semantic review notes:

- I verified the linked issue #1314, refreshed pre-audit, and independent gate. The approved first-slice class is `tier5.create_flow_instance_fixture_admission_current_spec`.
- The implementation closes all three Tier5 fixtures together and removes the stale Tier5 closed-#416 exclusions. Remaining #416 hits are Tier4/Tier11 split siblings, not hidden same-class Tier5 interpreters.
- The prior unresolved duplicate-proof thread is obsolete on current head: the duplicate fixture now asserts the second trigger receipt as `dead_letter`, and the helper checks the platform pipeline receipt side effects. I resolved that thread.
- Spec compliance checked against `platform-spec.yaml` `create_flow_instance`, `dynamic_instance_lifecycle`, `config_from_payload_alignment`, and `auto_emit_on_create_surface`. No platform spec change is required because this PR admits fixtures under existing semantics rather than changing runtime semantics.
- Watchlist decision: primary mapping to `/Users/youmew/dev/swarm-docs/docs/watchlists/maintenance-and-cleanup.yaml#invariant_suite_coverage` is valid. The PR proof audit’s `semantic-correctness.yaml#legacy_fixture_drift_after_runtime_contract_migrations` reference does not exist; I am not treating it as a live tracker. The historical semantic caution is covered by `semantic-correctness.yaml#primitive_only_cross_flow_authored_contract_migration`; no watchlist file edit is required for this PR.

Local proof run:

- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_RealRuntime/(test-create-flow-instance|test-create-flow-instance-config|test-create-flow-instance-duplicate)$' -count=1`
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_(AreExplicitlyClassified|RealRuntime)$' -count=1`
- `go test ./internal/runtime/swarmflowtest -run 'TestCatalogFixtures_UseCanonicalCreateFlowInstanceAuthoring|TestValidateCatalogExpectedDocument' -count=1`
- `go test ./internal/runtime/cataloge2e -run 'TestTier(9|11)' -count=1`
- `go test ./internal/runtime/cataloge2e -count=1`
- `go test ./internal/runtime/manager -run 'TestActivateFlowInstance(AutoEmitPublishesConfigPayloadWithoutActivationContext|QueuedAutoEmitUsesProjectedConfigPayload|AutoEmitFailsClosedOnUndeclaredEnvelopeLikeConfigField)' -count=1`
- `go test ./internal/runtime/pipeline -run 'TestCreateFlowInstance(ResolvesConfigFromBindings|RejectsMissingRequiredSiblingFields|RejectsEmptyConfigFromBindings|RejectsEmptyResolvedConfig)' -count=1`
- `go test ./internal/store -run 'TestSQLiteDynamicFlowActivationRequiredAgentsUsePipelineTransaction|TestSQLiteDynamicFlowActivationConcurrentFanOutChildrenPersist' -count=1` reproduced the known unrelated `event bus does not support derived flow-instance routing ...` failures.
- `git diff --check d6c64f3c..HEAD` passed, but `gofmt -l internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go` fails.

Closure assessment: code/proof coverage is sufficient for the approved #1314 first slice once formatting/CI are repaired. Merge recommendation: changes requested; do not merge until gofmt is applied and CI is green or explicitly waived by lead.

**Comment by yazzaoui** [comment]
## Review checklist

- Guideline checks: pre-audit and independent gate verified; PR proof audit verified; unresolved duplicate-proof thread verified obsolete and resolved; current CI failure checked.
- Spec compliance: existing `platform-spec.yaml` `create_flow_instance`, dynamic lifecycle, `config_from_payload_alignment`, and `auto_emit_on_create_surface` semantics satisfied; no spec update required.
- Failure-class coverage: all three Tier5 `create_flow_instance` fixtures admitted together; Tier4/Tier11 #416 siblings remain explicitly split.
- Closure level: `tier5.create_flow_instance_fixture_admission_current_spec` eliminated at code/proof level, pending formatting repair.
- Watchlist decision: no watchlist file change; primary mapping `maintenance-and-cleanup.yaml#invariant_suite_coverage`; semantic caution handled as historical only, not live tracker.
- Residual risk: CI `test` currently fails on gofmt for `internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go`; known unrelated `internal/store` dynamic-routing tests also reproduce locally.
- Risk level: low after formatting/CI repair.
- Merge recommendation: do not merge yet; apply gofmt and rerun CI first.

**Comment by yazzaoui** [comment]
## Rebase / Review Follow-up

Rebased PR #1318 onto current `origin/master` at `8b95eef2` (`test: harden serve readiness lifecycle tests`) and force-pushed the rebased branch.

Actions taken:
- Applied `gofmt` repair for `internal/runtime/cataloge2e/tier5_lifecycle_e2e_test.go`.
- Added the new `receipt_outcome` / `receipt_error_contains` expected-yaml fields to the parallel `swarmflowtest` catalog schema so catalog parsing stays aligned across harnesses.

Proof on the final rebased head:
- `git diff --check` passed.
- `env GOCACHE=/tmp/swarm-go-cache-1314-rebase go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_(AreExplicitlyClassified|RealRuntime)$' -count=1` passed.
- `env GOCACHE=/tmp/swarm-go-cache-1314-rebase go test ./internal/runtime/swarmflowtest -count=1` passed.

Current upstream blocker:
- `env GOCACHE=/tmp/swarm-go-cache-1314-rebase go test ./cmd/swarm -count=1` fails to build on the rebased head with `cmd/swarm/main_test.go:3733:2: undefined: waitForServeReadyLine`.
- This PR has no `cmd/swarm` diff. The failing symbol is introduced by the current `origin/master` commit `8b95eef2`, so I did not patch it inside #1314.

**Comment by yazzaoui** [comment]
## Upstream Failure Verification

I rechecked the current base after the concern that other recent PRs looked green.

Evidence that this is on current `origin/master`, not PR #1318:
- Current base is `8b95eef2` (`test: harden serve readiness lifecycle tests`).
- GitHub check run for that exact commit has `test` = failure: `vet: cmd/swarm/main_test.go:3733:2: undefined: waitForServeReadyLine`.
- A clean detached worktree at `origin/master` reproduces the same failure with `go test ./cmd/swarm -count=1`.
- PR #1318 has no `cmd/swarm` diff.

I’m leaving this outside the #1314 PR boundary unless lead explicitly wants this PR to absorb the upstream `cmd/swarm` test helper repair.

**Comment by yazzaoui** [comment]
Opened upstream blocker tracker: #1324 (`cmd/swarm test build fails: missing waitForServeReadyLine helper`).

**Review by yazzaoui — COMMENTED** [review]
Findings: none in the PR code or proof surface.

This re-review supersedes my earlier formatting blocker. Current head `785dc9a4` fixes the gofmt issue and adds the missing `swarmflowtest` expected-yaml fields for `receipt_outcome` / `receipt_error_contains`, so the new duplicate receipt assertion is parsed consistently across catalog harnesses.

Process / semantic review:

- Linked issue #1314, refreshed pre-audit, and independent gate were rechecked. The approved class remains `tier5.create_flow_instance_fixture_admission_current_spec`.
- The PR closes all three Tier5 `create_flow_instance` fixture manifestations together: base, config, and duplicate. No Tier5 same-concept interpreter remains hidden in the exclusion map.
- Tier5 closed-#416 references are removed. Remaining #416 references are Tier4/Tier11 split siblings, consistent with the gate.
- The prior duplicate-create inline concern remains resolved on current head. The duplicate fixture asserts the second trigger pipeline receipt as `dead_letter` with the expected duplicate instance error, and the helper checks the platform pipeline receipt side effects.
- Spec compliance checked against existing `platform-spec.yaml` `create_flow_instance`, `dynamic_instance_lifecycle`, `config_from_payload_alignment`, and `auto_emit_on_create_surface`. No `platform-spec.yaml` update is required because this PR admits fixtures under existing semantics rather than changing runtime semantics.
- The PR proof audit still mentions `semantic-correctness.yaml#legacy_fixture_drift_after_runtime_contract_migrations`, which is not a real watchlist node. I am treating that as non-authoritative historical caution only. The valid mappings are `maintenance-and-cleanup.yaml#invariant_suite_coverage` and historical caution under `semantic-correctness.yaml#primitive_only_cross_flow_authored_contract_migration`; no watchlist file edit is required for this PR.

Local proof on PR head:

- `gofmt -l .` returned clean.
- `git diff --check` passed.
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_RealRuntime/(test-create-flow-instance|test-create-flow-instance-config|test-create-flow-instance-duplicate)$' -count=1` passed.
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_(AreExplicitlyClassified|RealRuntime)$' -count=1` passed.
- `go test ./internal/runtime/swarmflowtest -count=1` passed.

Merge-result proof against current `origin/master` (`7db64abb`):

- PR merged cleanly into a temporary worktree.
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_RealRuntime/(test-create-flow-instance|test-create-flow-instance-config|test-create-flow-instance-duplicate)$' -count=1` passed.
- `go test ./internal/runtime/cataloge2e -run 'TestTier5LifecycleCatalogFixtures_(AreExplicitlyClassified|RealRuntime)$' -count=1` passed.
- `go test ./internal/runtime/swarmflowtest -count=1` passed.
- `go test ./internal/runtime/cataloge2e -run 'TestTier(9|11)' -count=1` passed.
- `go test ./internal/runtime/cataloge2e -count=1` passed.
- `go test ./internal/runtime/manager -run 'TestActivateFlowInstance(AutoEmitPublishesConfigPayloadWithoutActivationContext|QueuedAutoEmitUsesProjectedConfigPayload|AutoEmitFailsClosedOnUndeclaredEnvelopeLikeConfigField)' -count=1` passed.
- `go test ./internal/runtime/pipeline -run 'TestCreateFlowInstance(ResolvesConfigFromBindings|RejectsMissingRequiredSiblingFields|RejectsEmptyConfigFromBindings|RejectsEmptyResolvedConfig)' -count=1` passed.

Residual / CI:

- GitHub `test` check is still red, but the current failure is `cmd/swarm/main_test.go:3733:2: undefined: waitForServeReadyLine`.
- A clean current-`origin/master` worktree reproduces that same `go test ./cmd/swarm -count=1` build failure.
- PR #1318 has no `cmd/swarm` diff, and the upstream failure is tracked by #1324.

Closure assessment: `tier5.create_flow_instance_fixture_admission_current_spec` is eliminated for the approved #1314 first slice. Concept-wide drift reduction is real for the Tier5 class; Tier4/Tier11 stale #416 siblings and #1304 remain explicitly split and tracked/separate.

Merge recommendation: code/proof is acceptable. Do not require PR #1318 to absorb #1324. Merge is reasonable only after the `test` check is rerun green from an upstream #1324 fix, or after lead explicitly waives the unrelated #1324 CI failure.

**Comment by yazzaoui** [comment]
## Re-review checklist

- Guideline checks: issue #1314, refreshed pre-audit, independent gate, PR proof audit, PR comments, inline review thread, and current CI state rechecked.
- Spec compliance: existing `platform-spec.yaml` `create_flow_instance`, dynamic lifecycle, `config_from_payload_alignment`, and `auto_emit_on_create_surface` semantics satisfied; no spec update required.
- Failure-class coverage: all three Tier5 `create_flow_instance` fixture manifestations are admitted and proven together; no remaining Tier5 same-concept bypass found.
- Concept-wide drift reduction: Tier5 closed-#416 exclusion drift removed; Tier4/Tier11 #416 siblings and #1304 remain split.
- Closure level: chosen class `tier5.create_flow_instance_fixture_admission_current_spec` eliminated.
- Watchlist decision: no file update; valid primary mapping is `maintenance-and-cleanup.yaml#invariant_suite_coverage`; semantic caution is covered by `semantic-correctness.yaml#primitive_only_cross_flow_authored_contract_migration`.
- Follow-up tracking: unrelated merge-result CI failure is already tracked by #1324.
- Risk level: low for PR code; medium merge-process risk while CI remains red from #1324.
- Merge recommendation: acceptable after #1324 is fixed and CI reruns green, or with explicit lead waiver for the unrelated #1324 failure.
